name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Build client
        run: cargo build --features client --verbose
      - name: Test
        run: cargo test --verbose
      - name: Test client
        run: cargo test --features client --verbose
